- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: nginx systemd
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started
