- name: Restart Postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Reload Postgresql
  ansible.builtin.service:
    name: postgresql
    state: reloaded

- name: Enable Postgresql
  ansible.builtin.systemd:
    name: postgresql
    enabled: true
    state: started
